Repository QuiiBz/next-international, pull requests merged in 2023-09, with the labels that each got.

#145 feat(next-international): use `notFound()` instead of throwing un-catchable error
  packages/next-international/src/app/client/create-use-current-locale.ts
  packages/next-international/src/app/server/get-locale-cache.tsx
Labels: enhancement

#146 fix(next-international): infinite redirect with `rewrite` strategy
  packages/next-international/src/app/middleware/index.ts
Labels: bug

#148 fix(next-international): non-string params translations return string
  packages/next-international/src/common/create-t.ts
Labels: bug

#150 refactor(next-international): load fallback locale immediately
  docs/pages/docs/app-setup.mdx
  docs/pages/docs/pages-setup.mdx
  examples/next-app/app/[locale]/client/layout.tsx
  examples/next-app/locales/server.ts
  examples/next-pages/pages/_app.tsx
  packages/next-international/src/app/client/create-i18n-provider-client.tsx
  packages/next-international/src/app/server/create-get-i18n.ts
  packages/next-international/src/app/server/create-get-scoped-i18n.ts
  packages/next-international/src/app/server/create-get-static-params.ts
  packages/next-international/src/app/server/index.ts
  packages/next-international/src/pages/create-i18n-provider.tsx
  packages/next-international/src/pages/index.ts
  packages/next-international/src/types.ts
Labels: bug

#153 feat(next-international): add `rewriteDefault` strategy
  docs/pages/docs/app-middleware-configuration.md
  packages/next-international/src/app/middleware/index.ts
  packages/next-international/src/types.ts
Labels: enhancement

#157 chore: add issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#164 fix(next-international): `useChangeLocale` with pages starting with a locale
  packages/next-international/src/app/client/create-use-change-locale.ts
  packages/next-international/src/app/client/index.ts
Labels: bug

#174 fix(next-international): fallbackLocale with dot-notation TS error
  packages/next-international/src/app/client/create-i18n-provider-client.tsx
  packages/next-international/src/types.ts
Labels: bug

#175 fix(next-international): respect rewriteDefault strategy when changing locale
  packages/next-international/src/app/middleware/index.ts
Labels: bug

#177 chore: update sponsors url
  assets/sponsors.svg
  docs/pages/index.mdx
  packages/next-international/README.md
Labels: documentation

#185 chore: add sherif to lint monorepo
  .github/workflows/sherif.yml
  package.json
Labels: enhancement

#204 feat(next-international): redirect default with `rewriteDefault`
  docs/package.json
  examples/next-app/package.json
  packages/next-international/src/app/middleware/index.ts
  pnpm-lock.yaml
Labels: enhancement
