Repository QuiiBz/next-international, pull requests merged in 2023-10, with the labels that each got.

#202 feat(next-international): Static Rendering with loading for Client Components
  docs/package.json
  docs/pages/docs/app-setup.mdx
  examples/next-app/app/[locale]/client.tsx
  examples/next-app/app/[locale]/client/layout.tsx
  examples/next-app/app/[locale]/page.tsx
  examples/next-app/app/[locale]/provider.tsx
  examples/next-app/locales/client.ts
  examples/next-app/next.config.js
  packages/next-international/src/app/client/create-i18n-provider-client.tsx
  packages/next-international/src/app/client/index.ts
  packages/next-international/src/types.ts
Labels: bug, enhancement

#207 feat(next-international): preserve search params
  docs/pages/docs/app-get-change-locale.md
  examples/next-app/app/[locale]/layout.tsx
  examples/next-app/app/[locale]/switch.tsx
  packages/next-international/src/app/client/create-use-change-locale.ts
  packages/next-international/src/types.ts
Labels: enhancement

#215 chore(docs): add `'use client'` annotation
  docs/pages/docs/app-setup.mdx
Labels: documentation

#217 feat(next-international): plurals with count 0 works with `#zero`
  docs/pages/docs/app-plurals.md
  docs/pages/docs/pages-plurals.md
  packages/next-international/__tests__/use-i18n.test.tsx
  packages/next-international/__tests__/utils/en.ts
  packages/next-international/src/common/create-t.ts
Labels: enhancement

#232 feat(next-international): export internal functions
  packages/next-international/src/index.ts
Labels: enhancement

#236 fix(international-types): flatten works with dot & object notation
  packages/international-types/index.ts
Labels: bug

#226 chore: bump next & nextra
  .github/workflows/sherif.yml
  examples/next-app/package.json
  examples/next-pages/package.json
  packages/next-international/package.json
  pnpm-lock.yaml
Labels: dependencies

#234 feat(next-international): only trigger suspense on first load
  examples/next-app/locales/client.ts
  packages/next-international/src/app/client/create-i18n-provider-client.tsx
  packages/next-international/src/app/client/create-use-change-locale.ts
  packages/next-international/src/app/client/index.ts
Labels: enhancement

#246 fix(next-international): rewrite strategies keep search params
  packages/next-international/src/app/middleware/index.ts
Labels: bug
