Repository QuiiBz/next-international, pull requests merged in 2023-07, with the labels that each got.

#57 fix(app-router): typesafe `getCurrentLocale` in Server Components
  packages/next-international/src/app/server/create-get-current-locale.ts
  packages/next-international/src/app/server/index.ts
Labels: enhancement

#59 fix(next-international): include types in files
  packages/next-international/package.json
Labels: bug

#61 fix(app): React Server Components issues
  examples/next-app/app/[locale]/layout.tsx
  examples/next-app/app/[locale]/page.tsx
  examples/next-app/app/[locale]/subpage/page.tsx
  examples/next-app/locales/server.ts
  examples/next-app/next.config.js
  examples/next-app/package.json
  examples/next-pages/next.config.js
  examples/next-pages/package.json
  package.json
  packages/next-international/README.md
  packages/next-international/package.json
  packages/next-international/src/app/middleware/index.ts
  packages/next-international/src/app/server/create-get-current-locale.ts
  packages/next-international/src/app/server/create-get-i18n.ts
  packages/next-international/src/app/server/create-get-scoped-i18n.ts
  packages/next-international/src/app/server/create-get-static-params.ts
  packages/next-international/src/app/server/create-i18n-provider-server.tsx
  packages/next-international/src/app/server/get-locale-cache.tsx
  packages/next-international/src/app/server/index.ts
  pnpm-lock.yaml
Labels: bug

#69 fix(next-international): nested objects locales in App Router
  packages/next-international/src/app/client/create-i18n-provider-client.tsx
  packages/next-international/src/app/server/create-get-i18n.ts
  packages/next-international/src/app/server/create-get-scoped-i18n.ts
  packages/next-international/src/common/flatten-locale.ts
  packages/next-international/src/pages/create-i18n-provider.tsx
Labels: bug

#70 chore: documentation fixes
  packages/next-international/README.md
Labels: documentation

#71 chore: fix docs
  packages/next-international/README.md
Labels: documentation

#75 feat: add plurals support
  examples/next-app/app/[locale]/client/page.tsx
  examples/next-app/app/[locale]/page.tsx
  examples/next-app/locales/en.ts
  examples/next-app/locales/fr.ts
  examples/next-pages/locales/en.ts
  examples/next-pages/locales/fr.ts
  examples/next-pages/pages/index.tsx
  examples/next-pages/pages/ssr-ssg.tsx
  packages/international-types/index.ts
  packages/next-international/README.md
  packages/next-international/src/app/client/create-i18n-provider-client.tsx
  packages/next-international/src/app/client/index.ts
  packages/next-international/src/app/server/create-get-i18n.ts
  packages/next-international/src/app/server/create-get-scoped-i18n.ts
  packages/next-international/src/common/create-t.ts
  packages/next-international/src/pages/create-i18n-provider.tsx
  packages/next-international/src/types.ts
Labels: enhancement

#78 feat: typesafe plural `count`
  packages/international-types/index.ts
  packages/next-international/README.md
  packages/next-international/src/common/create-t.ts
Labels: enhancement

#80 fix(international-types): plural tags
  packages/international-types/index.ts
  packages/next-international/README.md
Labels: bug

#82 chore: improve README
  packages/next-international/README.md
Labels: documentation
